### ISSUE TITLE
Suggestion: alias "a" to "an"

### ISSUE THREAD

**Issue by ghost** [tj/should.js#53]
Bit pedantic I know, but works nice with an('object') :)

**Comment by gabrielf** [comment]
I agree that this is a good idea but it looks like it might be problematic since 'an' is currently a getter used to support constructs like: foo.should.be.an.instanceOf('string') and it does not seem to be possible to have a getter that can be called like a function which would be necessary for foo.should.be.an('object')

Is there perhaps an alternative solution? foo.should.beAn('object') is a suggestion but looks a bit ugly to my eyes.

**Comment by btd** [comment]
I prefer that `a` will be the same as `an`, just getter and replace `a(srt)` with something like this:
`user.should.have.type('object')`.

Any ideas?

**Comment by gabrielf** [comment]
That sound like a good idea. It is less surprising that 'a' and 'an' is the same kind of thing. Even though it would be a breaking change I still support it.

**Comment by btd** [comment]
Fixed in next mayor version.
